microsoft/powerbi-powershell

- README.md
- scripts/Build.ps1
- scripts/PrepManualTesting.ps1
- src/Common/Commands.Common.Test/Commands.Common.Test.csproj
- src/Common/Commands.Common.Test/TestUtilities.cs
- src/Common/Commands.Common/PowerBICmdlet.cs
- src/Modules/Profile/Commands.Profile.Test/Commands.Profile.Test.csproj
- src/Modules/Profile/Commands.Profile.Test/ProfileTestUtilities.cs
- src/Modules/Workspaces/Commands.Workspaces.Test/Commands.Workspaces.Test.csproj
- src/Modules/Workspaces/Commands.Workspaces.Test/SetPowerBIWorkspaceTests.cs
- src/Modules/Workspaces/Commands.Workspaces.Test/WorkspacesTestUtilities.cs
- src/Modules/Workspaces/Commands.Workspaces/MicrosoftPowerBIMgmt.Workspaces.psd1
- src/Modules/Workspaces/Commands.Workspaces/SetPowerBIWorkspace.cs
- src/Modules/Workspaces/Commands.Workspaces/help/MicrosoftPowerBIMgmt.Workspaces.md
- src/Modules/Workspaces/Commands.Workspaces/help/Set-PowerBIWorkspace.md
- src/NuGet.config
- The Set-PowerBIWorkspace cmdlet works for the Organization scope; the Individual scope is not supported yet
- Add NotImplementedException as a terminating error
- Add test utilities classes to reduce test code duplication
- Fix local build script error
>  Add Set-PowerBIWorkspace cmdlet

- src/Common/Commands.Common/settings.json
- src/Common/Common.Abstractions/PowerBIEnvironmentType.cs
- src/Modules/Profile/Commands.Profile/help/Connect-PowerBIServiceAccount.md
- src/Modules/Workspaces/Commands.Workspaces/help/Add-PowerBIWorkspaceUser.md
Added environments Germany, USGov and fixed China.
> Added Germany, USGov and updated China environments

- scripts/PublishModules.ps1
- src/Modules/Reports/Commands.Reports/MicrosoftPowerBIMgmt.Reports.psd1
* Fixed tags in Report *.psd1 file which prevents publishing
* Fix to NuGet source for uploading to PowerShell Gallery
> Fixes for publishing

- ROADMAP.md
- src/Common/Common.Api/Datasets/DatasetsClient.cs
- src/Common/Common.Api/Datasets/IDatasetsClient.cs
- src/Modules/Data/Commands.Data.Test/GetPowerBIDatasourceTests.cs
- src/Modules/Data/Commands.Data.Test/GetPowerBITableTests.cs
- src/Modules/Data/Commands.Data/Commands.Data.csproj
- src/Modules/Data/Commands.Data/GetPowerBITable.cs
- src/Modules/Data/Commands.Data/MicrosoftPowerBIMgmt.Data.psd1
- src/Modules/Data/Commands.Data/help/Get-PowerBITable.md
- src/Modules/Data/Commands.Data/help/MicrosoftPowerBIMgmt.Data.md
- src/Modules/Profile/Commands.Profile.Test/InvokePowerBIRestMethodTests.cs
- src/Modules/Profile/Commands.Profile.Test/ProfileTestUtilities.cs
As part of Data module, added Get-PowerBITable cmdlet
Fixed road map explanation that table belongs to dataset, not data source.
> Add Get-PowerBITable #45

- ROADMAP.md
- src/Common/Common.Abstractions/PowerBIDataType.cs
- src/Common/Common.Api/Datasets/Column.cs
- src/Common/Common.Api/Datasets/Dataset.cs
- src/Common/Common.Api/Datasets/DatasetsClient.cs
- src/Common/Common.Api/Datasets/Datasource.cs
- src/Common/Common.Api/Datasets/DatasourceConnectionDetails.cs
- src/Common/Common.Api/Datasets/IDatasetsClient.cs
- src/Common/Common.Api/Datasets/Measure.cs
- src/Common/Common.Api/Datasets/PowerBIDataType.cs
- src/Common/Common.Api/Datasets/Relationship.cs
- src/Common/Common.Api/Datasets/Row.cs
- src/Common/Common.Api/Datasets/Table.cs
- src/Modules/Data/Commands.Data.Test/AddPowerBIDatasetTests.cs
- src/Modules/Data/Commands.Data/AddPowerBIDataset.cs
- src/Modules/Data/Commands.Data/Commands.Data.csproj
- src/Modules/Data/Commands.Data/MicrosoftPowerBIMgmt.Data.psd1
- src/Modules/Data/Commands.Data/NewPowerBIColumn.cs
- src/Modules/Data/Commands.Data/NewPowerBIDataset.cs
- src/Modules/Data/Commands.Data/NewPowerBITable.cs
- src/Modules/Data/Commands.Data/help/Add-PowerBIDataset.md
- src/Modules/Data/Commands.Data/help/MicrosoftPowerBIMgmt.Data.md
- src/Modules/Data/Commands.Data/help/New-PowerBIColumn.md
- src/Modules/Data/Commands.Data/help/New-PowerBIDataset.md
- src/Modules/Data/Commands.Data/help/New-PowerBITable.md
Add-PowerBIDataset and related cmdlets
New-PowerBIDataset
New-PowerBITable
New-PowerBIColumn
Added implicit converter to models.
Added md files.
Add DataType enum
> Add-PowerBIDataset cmdlets

- scripts/PrepManualTesting.ps1
- src/Common/Commands.Common/PowerBICmdlet.cs
- src/Common/Common.Client/PowerBIClientFactory.cs
- src/Common/Common.Client/PowerBIHttpClientHandler.cs
- src/Modules/Data/Commands.Data/help/New-PowerBIColumn.md
- src/Modules/Profile/Commands.Profile/InvokePowerBIRestMethod.cs
> Adding UserAgent for cmdlets

- src/Common/Common.Api/Datasets/DatasetsClient.cs
- src/Common/Common.Api/Datasets/IDatasetsClient.cs
- src/Common/Common.Api/Datasets/Table.cs
- src/Modules/Data/Commands.Data.Test/AddPowerBIRowsTests.cs
- src/Modules/Data/Commands.Data.Test/RemovePowerBIRowsTests.cs
- src/Modules/Data/Commands.Data/AddPowerBIRows.cs
- src/Modules/Data/Commands.Data/MicrosoftPowerBIMgmt.Data.psd1
- src/Modules/Data/Commands.Data/RemovePowerBIRows.cs
- src/Modules/Data/Commands.Data/help/Add-PowerBIDataset.md
- src/Modules/Data/Commands.Data/help/Add-PowerBIRows.md
- src/Modules/Data/Commands.Data/help/MicrosoftPowerBIMgmt.Data.md
- src/Modules/Data/Commands.Data/help/New-PowerBIColumn.md
- src/Modules/Data/Commands.Data/help/Remove-PowerBIRows.md
Added two cmdlets
- Add-PowerBIRows
- Remove-PowerBIRows
> Support add/remove Power BI rows

- examples/Export-RefreshHistory.ps1
* Adding Export-RefreshHistory.ps1 to newly created examples folder
> Adding example script Export-RefreshHistory.ps1

- README.md
- examples/MigrateUsersToPro.ps1
* Updated README with more examples
* Added MigrateUsersToPro.ps1 in examples folder
> Added MigrateUsersToPro.ps1 and updated README with more examples

- src/Modules/Admin/Commands.Admin.Test/AddPowerBIEncryptionKeyTests.cs
- src/Modules/Admin/Commands.Admin.Test/GetPowerBIWorkspaceEncryptionStatusTests.cs
- src/Modules/Admin/Commands.Admin.Test/SwitchPowerBIEncryptionKeyTests.cs
- src/Modules/Admin/Commands.Admin/AddPowerBIEncryptionKey.cs
- src/Modules/Admin/Commands.Admin/Commands.Admin.csproj
- src/Modules/Admin/Commands.Admin/Constants.cs
- src/Modules/Admin/Commands.Admin/GetPowerBIWorkspaceEncryptionStatus.cs
- src/Modules/Admin/Commands.Admin/Microsoft.PowerBI.Commands.Admin.format.ps1xml
- src/Modules/Admin/Commands.Admin/MicrosoftPowerBIMgmt.Admin.psd1
- src/Modules/Admin/Commands.Admin/SetPowerBIEncryptionKey.cs
- src/Modules/Admin/Commands.Admin/SwitchPowerBIEncryptionKey.cs
- src/Modules/Admin/Commands.Admin/help/Add-PowerBIEncryptionKey.md
- src/Modules/Admin/Commands.Admin/help/Get-PowerBIEncryptionKey.md
- src/Modules/Admin/Commands.Admin/help/Get-PowerBIWorkspaceEncryptionStatus.md
- src/Modules/Admin/Commands.Admin/help/MicrosoftPowerBIMgmt.Admin.md
- src/Modules/Admin/Commands.Admin/help/Switch-PowerBIEncryptionKey.md
- Print the error detail content when API provides error
- Fixed formatting bug in Get-WorkspaceEncryptionStatus where the encryption status was printed as Class Name instead of value
> Minor bug fixes for BYOK

- scripts/GetNetstandardAssembly.ps1
> Fix for GetNetstandardAssembly

- build/Microsoft.PowerBI.Build.targets
- src/Modules/Reports/Commands.Reports/help/MicrosoftPowerBIMgmt.Reports.md
* Fix for PDB generation for debug builds
* MicrosoftPowerBIMgmt.Reports.md wasn't fully generated
> Fix for PDB generation for Debug builds

- README.md
Updating readme to match what is on https://docs.microsoft.com/en-us/powershell/power-bi/overview
> Syncing readme between docs.microsoft.com and GitHub

- src/Common/Common.Api/Common.Api.csproj
- src/Modules/Admin/Commands.Admin.Test/GetPowerBIActivityEventsTests.cs
- src/Modules/Admin/Commands.Admin/GetPowerBIActivityEvents.cs
- src/Modules/Admin/Commands.Admin/help/Get-PowerBIActivityEvents.md
Added a new parameter for the Get-PowerBIActivityEvents cmdlet to support filtering of the results based on the user email.
> Added support for filtering audit activity events based on userId(emailId).

- src/Common/Common.Api/ActivityEvent/ActivityEventResponse.cs
- src/Common/Common.Api/ActivityEvent/OutputType.cs
- src/Common/Common.Api/Admin/AdminClient.cs
- src/Common/Common.Api/Admin/IAdminClient.cs
- src/Common/Common.Api/Common.Api.csproj
- src/Common/Common.Api/PowerBIFeatureNotAvailableError.cs
- src/Common/Common.Api/PowerBIFeatureNotAvailableErrorType.cs
- src/Modules/Admin/Commands.Admin.Test/GetPowerBIActivityEventsTests.cs
- src/Modules/Admin/Commands.Admin/Commands.Admin.csproj
- src/Modules/Admin/Commands.Admin/GetPowerBIActivityEvents.cs
- src/Modules/Admin/Commands.Admin/MicrosoftPowerBIMgmt.Admin.psd1
- src/Modules/Admin/Commands.Admin/help/Get-PowerBIActivityEvents.md
- src/Modules/Admin/Commands.Admin/help/MicrosoftPowerBIMgmt.Admin.md
- src/Modules/Data/Commands.Data/help/Get-PowerBIDataset.md
This is the PR for checking in the dev branch into master for Get-PowerBIAdminActivityEvents cmdlet.
> Get-PowerBIAdminActivityEvents cmdlet to retrieve audit activity events

- ReleaseNotes.md
Update release notes in preparation for next release. This release contains the ability to add service principals and groups to workspaces via the `Add-PowerBIWorkspaceUser` cmdlet.
> Add release notes for updates to Add-PowerBIWorkspaceUser.

- examples/GetPowerBIActivityEvents.ps1
- src/Modules/Admin/Commands.Admin.Test/GetPowerBIActivityEventTests.cs
- src/Modules/Admin/Commands.Admin/MicrosoftPowerBIMgmt.Admin.psd1
- src/Modules/Admin/Commands.Admin/help/Get-PowerBIActivityEvent.md
- src/Modules/Admin/Commands.Admin/help/MicrosoftPowerBIMgmt.Admin.md
* Revert "undo auto changes"
This reverts commit 67c10726536120d2bb6cac0216f639ff676f388a.
* Revert "Removing Get-PowerBIActivityEvent cmdlet"
This reverts commit c3a699eca8af2bc51a29b61f134a06351ad6053d.
* Address feedback
> Reintroduce get activity events (#198)

- src/Common/Commands.Common/PowerBISettings.cs
Environment configuration requires TLS 1.2 protocol, and for some users this is not the default protocol in PowerShell, which will cause failures like in loing
> Enforce TLS 1.2 when calling global discovery config

- CONTRIBUTING.md
- ReleaseNotes.md
Reverts microsoft/powerbi-powershell#281
> Revert "Update doc for MSAL"

- scripts/GetNetstandardAssembly.ps1
- src/Common/Commands.Common.Test/PowerBISettingsTests.cs
- src/Common/Commands.Common/settings.json
- src/Common/Common.Abstractions/PowerBIEnvironmentType.cs
- src/Modules/Profile/Commands.Profile.Test/ConnectPowerBIServiceAccountTests.cs
This is to add support for debug environment DAILY
> Added the support for daily
